[2024-04-08T08:31:49.405+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: real_estates.transform_normalize manual__2024-04-08T07:30:32.722267+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
