[2024-04-08T08:34:01.257+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.transform_parse_address manual__2024-04-08T07:30:32.722267+00:00 [queued]>
[2024-04-08T08:34:01.277+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.transform_parse_address manual__2024-04-08T07:30:32.722267+00:00 [queued]>
[2024-04-08T08:34:01.278+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 3
[2024-04-08T08:34:01.310+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform_parse_address> on 2024-04-08 07:30:32.722267+00:00
[2024-04-08T08:34:01.328+0000] {standard_task_runner.py:60} INFO - Started process 562 to run task
[2024-04-08T08:34:01.335+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'transform_parse_address', 'manual__2024-04-08T07:30:32.722267+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpg4jzt84d']
[2024-04-08T08:34:01.341+0000] {standard_task_runner.py:88} INFO - Job 345: Subtask transform_parse_address
[2024-04-08T08:34:01.750+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.transform_parse_address manual__2024-04-08T07:30:32.722267+00:00 [running]> on host 0a1174cdb8a2
[2024-04-08T08:34:02.038+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='transform_parse_address' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T07:30:32.722267+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T07:30:32.722267+00:00'
[2024-04-08T08:34:02.050+0000] {__init__.py:98} WARNING - Town 東峰町 not in database
[2024-04-08T08:34:02.052+0000] {__init__.py:98} WARNING - Town 今井町 not in database
[2024-04-08T08:34:02.053+0000] {__init__.py:98} WARNING - Town 押立町 not in database
[2024-04-08T08:34:02.054+0000] {__init__.py:98} WARNING - Town 戸塚町 not in database
[2024-04-08T08:34:02.054+0000] {__init__.py:98} WARNING - Town 甲南町 not in database
[2024-04-08T08:34:02.056+0000] {__init__.py:98} WARNING - Town 大門町 not in database
[2024-04-08T08:34:02.057+0000] {__init__.py:98} WARNING - Town 南町 not in database
[2024-04-08T08:34:02.057+0000] {__init__.py:98} WARNING - Town 松見町 not in database
[2024-04-08T08:34:02.058+0000] {__init__.py:98} WARNING - Town 林島町 not in database
[2024-04-08T08:34:02.059+0000] {__init__.py:98} WARNING - Town 須惠町 not in database
[2024-04-08T08:34:02.060+0000] {__init__.py:98} WARNING - Town 奈良津町 not in database
[2024-04-08T08:34:02.061+0000] {__init__.py:98} WARNING - Town 柏町 not in database
[2024-04-08T08:34:02.061+0000] {__init__.py:98} WARNING - Town 北野町 not in database
[2024-04-08T08:34:02.062+0000] {__init__.py:98} WARNING - Town 西町 not in database
[2024-04-08T08:34:02.063+0000] {__init__.py:98} WARNING - Town 川口町 not in database
[2024-04-08T08:34:02.064+0000] {__init__.py:98} WARNING - Town 西枇杷島町 not in database
[2024-04-08T08:34:02.064+0000] {__init__.py:98} WARNING - Town 天道町 not in database
[2024-04-08T08:34:02.065+0000] {__init__.py:98} WARNING - Town 小手指元町 not in database
[2024-04-08T08:34:02.065+0000] {__init__.py:98} WARNING - Town 三河安城本町 not in database
[2024-04-08T08:34:02.066+0000] {__init__.py:98} WARNING - Town 幸町 not in database
[2024-04-08T08:34:02.067+0000] {__init__.py:98} WARNING - Town 北玉垣町 not in database
[2024-04-08T08:34:02.068+0000] {__init__.py:98} WARNING - Town 千歳町 not in database
[2024-04-08T08:34:02.068+0000] {__init__.py:98} WARNING - Town 本町 not in database
[2024-04-08T08:34:02.069+0000] {__init__.py:98} WARNING - Town 鴨居町 not in database
[2024-04-08T08:34:02.069+0000] {__init__.py:98} WARNING - Town 伊勢田町 not in database
[2024-04-08T08:34:02.071+0000] {__init__.py:98} WARNING - Town 元町 not in database
[2024-04-08T08:34:02.071+0000] {__init__.py:98} WARNING - Town 飯山満町 not in database
[2024-04-08T08:34:02.072+0000] {__init__.py:98} WARNING - Town 千住緑町 not in database
[2024-04-08T08:34:02.074+0000] {taskinstance.py:2731} ERROR - Task failed with exception
  + Exception Group Traceback (most recent call last):
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
  |     result = _execute_callable(context=context, **execute_callable_kwargs)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
  |     return execute_callable(context=context, **execute_callable_kwargs)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
  |     return_value = super().execute(context)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
  |     return_value = self.execute_callable()
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
  |     return self.python_callable(*self.op_args, **self.op_kwargs)
  |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/__init__.py", line 10, in transform_parse_address
  |     return trio.run(_transform_parse_address, data)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 2288, in run
  |     raise runner.main_task_outcome.error
  |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 57, in _transform_parse_address
  |     nursery.start_soon(parse_address, item, item["address"], parsed_data)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 954, in __aexit__
  |     raise combined_error_from_nursery
  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 64, in parse_address
    |     address_dict = parse(address)
    |   File "/home/airflow/.local/lib/python3.8/site-packages/japanese_address/__init__.py", line 89, in parse
    |     parsed["ward_eng"] = JAPANESE_WARDS[parsed["ward"]]
    | KeyError: '平松本町字上り戸721番16、722番16（従前地）（宇都宮都市計画事業宇都宮大学東南部第1土地区'
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 64, in parse_address
    |     address_dict = parse(address)
    |   File "/home/airflow/.local/lib/python3.8/site-packages/japanese_address/__init__.py", line 89, in parse
    |     parsed["ward_eng"] = JAPANESE_WARDS[parsed["ward"]]
    | KeyError: '飾磨区'
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 64, in parse_address
    |     address_dict = parse(address)
    |   File "/home/airflow/.local/lib/python3.8/site-packages/japanese_address/__init__.py", line 89, in parse
    |     parsed["ward_eng"] = JAPANESE_WARDS[parsed["ward"]]
    | KeyError: '飾磨区'
    +------------------------------------
[2024-04-08T08:34:02.092+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=transform_parse_address, execution_date=20240408T073032, start_date=20240408T083401, end_date=20240408T083402
[2024-04-08T08:34:02.116+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 345 for task transform_parse_address (Exceptions from Trio nursery (3 sub-exceptions); 562)
[2024-04-08T08:34:02.190+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T08:34:02.544+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
