[2024-04-08T00:29:53.041+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.transform_parse_address scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-08T00:29:53.060+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.transform_parse_address scheduled__2024-04-07T00:00:00+00:00 [queued]>
[2024-04-08T00:29:53.061+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-08T00:29:53.098+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): transform_parse_address> on 2024-04-07 00:00:00+00:00
[2024-04-08T00:29:53.113+0000] {standard_task_runner.py:60} INFO - Started process 75267 to run task
[2024-04-08T00:29:53.120+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'transform_parse_address', 'scheduled__2024-04-07T00:00:00+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmp37j48if4']
[2024-04-08T00:29:53.126+0000] {standard_task_runner.py:88} INFO - Job 266: Subtask transform_parse_address
[2024-04-08T00:29:53.542+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.transform_parse_address scheduled__2024-04-07T00:00:00+00:00 [running]> on host 05a350db99a0
[2024-04-08T00:29:53.886+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='transform_parse_address' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-07T00:00:00+00:00'
[2024-04-08T00:29:53.893+0000] {__init__.py:98} WARNING - Town 千住緑町 not in database
[2024-04-08T00:29:53.894+0000] {__init__.py:98} WARNING - Town 飯山満町 not in database
[2024-04-08T00:29:53.895+0000] {__init__.py:98} WARNING - Town 千歳町 not in database
[2024-04-08T00:29:53.897+0000] {__init__.py:98} WARNING - Town 幸町 not in database
[2024-04-08T00:29:53.898+0000] {__init__.py:98} WARNING - Town 小手指元町 not in database
[2024-04-08T00:29:53.899+0000] {__init__.py:98} WARNING - Town 三河安城本町 not in database
[2024-04-08T00:29:53.900+0000] {__init__.py:98} WARNING - Town 北野町 not in database
[2024-04-08T00:29:53.901+0000] {__init__.py:98} WARNING - Town 柏町 not in database
[2024-04-08T00:29:53.902+0000] {__init__.py:98} WARNING - Town 須惠町 not in database
[2024-04-08T00:29:53.904+0000] {__init__.py:98} WARNING - Town 松見町 not in database
[2024-04-08T00:29:53.904+0000] {__init__.py:98} WARNING - Town 南町 not in database
[2024-04-08T00:29:53.905+0000] {__init__.py:98} WARNING - Town 大門町 not in database
[2024-04-08T00:29:53.906+0000] {__init__.py:98} WARNING - Town 甲南町 not in database
[2024-04-08T00:29:53.907+0000] {__init__.py:98} WARNING - Town 戸塚町 not in database
[2024-04-08T00:29:53.908+0000] {__init__.py:98} WARNING - Town 押立町 not in database
[2024-04-08T00:29:53.908+0000] {__init__.py:98} WARNING - Town 今井町 not in database
[2024-04-08T00:29:53.910+0000] {__init__.py:98} WARNING - Town 東峰町 not in database
[2024-04-08T00:29:53.913+0000] {taskinstance.py:2731} ERROR - Task failed with exception
  + Exception Group Traceback (most recent call last):
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
  |     result = _execute_callable(context=context, **execute_callable_kwargs)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
  |     return execute_callable(context=context, **execute_callable_kwargs)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
  |     return_value = super().execute(context)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
  |     return_value = self.execute_callable()
  |   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
  |     return self.python_callable(*self.op_args, **self.op_kwargs)
  |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/__init__.py", line 8, in transform_parse_address
  |     return trio.run(_transform_parse_address, data)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 2288, in run
  |     raise runner.main_task_outcome.error
  |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 55, in _transform_parse_address
  |     nursery.start_soon(translate_item, item, translated_data)
  |   File "/home/airflow/.local/lib/python3.8/site-packages/trio/_core/_run.py", line 954, in __aexit__
  |     raise combined_error_from_nursery
  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 83, in translate_item
    |     addresses = parse(value)
    |   File "/home/airflow/.local/lib/python3.8/site-packages/japanese_address/__init__.py", line 89, in parse
    |     parsed["ward_eng"] = JAPANESE_WARDS[parsed["ward"]]
    | KeyError: '飾磨区'
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 83, in translate_item
    |     addresses = parse(value)
    |   File "/home/airflow/.local/lib/python3.8/site-packages/japanese_address/__init__.py", line 89, in parse
    |     parsed["ward_eng"] = JAPANESE_WARDS[parsed["ward"]]
    | KeyError: '飾磨区'
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/opt/airflow/dags/real_estates/homes_jp/transformers/parse_address.py", line 83, in translate_item
    |     addresses = parse(value)
    |   File "/home/airflow/.local/lib/python3.8/site-packages/japanese_address/__init__.py", line 89, in parse
    |     parsed["ward_eng"] = JAPANESE_WARDS[parsed["ward"]]
    | KeyError: '平松本町字上り戸721番16、722番16（従前地）（宇都宮都市計画事業宇都宮大学東南部第1土地区'
    +------------------------------------
[2024-04-08T00:29:53.931+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=transform_parse_address, execution_date=20240407T000000, start_date=20240408T002953, end_date=20240408T002953
[2024-04-08T00:29:53.954+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 266 for task transform_parse_address (Exceptions from Trio nursery (3 sub-exceptions); 75267)
[2024-04-08T00:29:54.015+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T00:29:54.357+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
