[2024-04-04T09:24:56.222+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.extract_real_estate_urls manual__2024-04-04T08:47:03.043176+00:00 [queued]>
[2024-04-04T09:24:56.240+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.extract_real_estate_urls manual__2024-04-04T08:47:03.043176+00:00 [queued]>
[2024-04-04T09:24:56.241+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 5
[2024-04-04T09:24:56.268+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): extract_real_estate_urls> on 2024-04-04 08:47:03.043176+00:00
[2024-04-04T09:24:56.283+0000] {standard_task_runner.py:60} INFO - Started process 4609 to run task
[2024-04-04T09:24:56.290+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'extract_real_estate_urls', 'manual__2024-04-04T08:47:03.043176+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpwc1ixl5n']
[2024-04-04T09:24:56.295+0000] {standard_task_runner.py:88} INFO - Job 231: Subtask extract_real_estate_urls
[2024-04-04T09:24:56.394+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.extract_real_estate_urls manual__2024-04-04T08:47:03.043176+00:00 [running]> on host 05a350db99a0
[2024-04-04T09:24:56.869+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='extract_real_estate_urls' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T08:47:03.043176+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T08:47:03.043176+00:00'
[2024-04-04T09:24:58.695+0000] {urls.py:36} INFO - Found 84560 real estates
[2024-04-04T09:24:58.701+0000] {urls.py:41} INFO - Found 2120 pages
[2024-04-04T09:25:14.808+0000] {urls.py:55} INFO - Batch 1/3 fetched 1000 pages
[2024-04-04T09:26:32.671+0000] {local_task_job_runner.py:280} WARNING - Recorded pid 4629 does not match the current pid 4609
[2024-04-04T09:26:32.675+0000] {process_utils.py:131} INFO - Sending 15 to group 4609. PIDs of all processes in the group: [4609]
[2024-04-04T09:26:32.676+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 4609
[2024-04-04T09:26:32.677+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-04T09:26:32.737+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/__init__.py", line 22, in extract_real_estate_urls
    return asyncio.run(_extract_real_estate_urls())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/urls.py", line 59, in _extract_real_estate_urls
    urls.extend(await extract_urls_at_page(response_text, batch_index * BATCH_SIZE + index + 1))
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/urls.py", line 99, in extract_urls_at_page
    soup = BeautifulSoup(response_text, "html.parser")
  File "/home/airflow/.local/lib/python3.8/site-packages/bs4/__init__.py", line 335, in __init__
    self._feed()
  File "/home/airflow/.local/lib/python3.8/site-packages/bs4/__init__.py", line 478, in _feed
    self.builder.feed(self.markup)
  File "/home/airflow/.local/lib/python3.8/site-packages/bs4/builder/_htmlparser.py", line 380, in feed
    parser.feed(markup)
  File "/usr/local/lib/python3.8/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.8/html/parser.py", line 199, in goahead
    i = self.updatepos(i, k)
  File "/usr/local/lib/python3.8/_markupbase.py", line 48, in updatepos
    def updatepos(self, i, j):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-04T09:26:32.747+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=extract_real_estate_urls, execution_date=20240404T084703, start_date=20240404T092629, end_date=20240404T092632
[2024-04-04T09:26:32.773+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 231 for task extract_real_estate_urls (Task received SIGTERM signal; 4609)
[2024-04-04T09:26:32.970+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4609, status='terminated', exitcode=1, started='09:24:55') (4609) terminated with exit code 1
